// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crp_api.Data;

#nullable disable

namespace crp_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220517100848_crp1")]
    partial class crp1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crp")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("crp_api.Models.Entities.Report", b =>
                {
                    b.Property<Guid>("REPORT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("BODY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("REPORTSTATUS_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("REPORTTYPE_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("USER_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("REPORT_ID");

                    b.HasIndex("REPORTSTATUS_ID");

                    b.HasIndex("REPORTTYPE_ID");

                    b.HasIndex("USER_ID");

                    b.ToTable("REPORTS", "crp");
                });

            modelBuilder.Entity("crp_api.Models.Entities.ReportLog", b =>
                {
                    b.Property<Guid>("REPORTLOG_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("REPORT_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("REPORTLOG_ID");

                    b.HasIndex("REPORT_ID");

                    b.ToTable("REPORTLOGS", "crp");
                });

            modelBuilder.Entity("crp_api.Models.Entities.ReportStatus", b =>
                {
                    b.Property<Guid>("REPORTSTATUS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("REPORTSTATUS_ID");

                    b.ToTable("REPORTSTATUSES", "crp");
                });

            modelBuilder.Entity("crp_api.Models.Entities.ReportType", b =>
                {
                    b.Property<Guid>("REPORTTYPE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("REPORTTYPE_ID");

                    b.ToTable("REPORTTYPES", "crp");
                });

            modelBuilder.Entity("crp_api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("USER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LNAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("USER_ID");

                    b.ToTable("USERS", "crp");
                });

            modelBuilder.Entity("crp_api.Models.Entities.Report", b =>
                {
                    b.HasOne("crp_api.Models.Entities.ReportStatus", "REPORTSTATUS")
                        .WithMany("REPORTS")
                        .HasForeignKey("REPORTSTATUS_ID");

                    b.HasOne("crp_api.Models.Entities.ReportType", "REPORTTYPE")
                        .WithMany("REPORTS")
                        .HasForeignKey("REPORTTYPE_ID")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("crp_api.Models.Entities.User", "USER")
                        .WithMany("REPORTS")
                        .HasForeignKey("USER_ID");

                    b.Navigation("REPORTSTATUS");

                    b.Navigation("REPORTTYPE");

                    b.Navigation("USER");
                });

            modelBuilder.Entity("crp_api.Models.Entities.ReportLog", b =>
                {
                    b.HasOne("crp_api.Models.Entities.Report", "REPORT")
                        .WithMany("REPORTLOGS")
                        .HasForeignKey("REPORT_ID")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.Navigation("REPORT");
                });

            modelBuilder.Entity("crp_api.Models.Entities.Report", b =>
                {
                    b.Navigation("REPORTLOGS");
                });

            modelBuilder.Entity("crp_api.Models.Entities.ReportStatus", b =>
                {
                    b.Navigation("REPORTS");
                });

            modelBuilder.Entity("crp_api.Models.Entities.ReportType", b =>
                {
                    b.Navigation("REPORTS");
                });

            modelBuilder.Entity("crp_api.Models.Entities.User", b =>
                {
                    b.Navigation("REPORTS");
                });
#pragma warning restore 612, 618
        }
    }
}
